### ISSUE TITLE
DataContext class missing methods

### ISSUE THREAD

**Issue by eminyuce** [CypressNorth/.NET-EF6-GenericRepository#1]
Hi,
DataContext class are missing lots of methods which are implemented in that BaseService class like Set method, SaveChangesAsync..
Am I missing any reference dll?

where are there?

**Comment by mombrea** [comment]
You have to pass your EF data context to the base service when you inherit from it like so:

```
public class AccountService : BaseService<ApplicationDbContext, Account>
{
    public AccountService(ApplicationDbContext context) : base(context) { }
}
```

The BaseService has several common methods for use but doesn't implement all of the standard DataContext methods. You can still use your DataContext directly to do things like call SaveChangesAsync.

When you go to use the service you'd initialize the ApplicationDbContext before you initialize the service itself, then you have the same context and access to both the services methods and the standard EF methods.

```
ApplicationDbContext db = new ApplicationDbContext();
AccountService service = new AccountService(db);

var account = await service.GetAsync(1);
account.name = "Joe";
account = await service.UpdateAsync(account,account.Id);

//or

var account = await db.Accounts.Where(x=>x.Id == 1).FirstOrDefaultAsync();
account.name = "Joe";
await db.SaveChangesAsync();
```

**Comment by eminyuce** [comment]
All right, Thank you for quick reply.  My project structure is a little different than what you suggested.

I am trying to implement a generic repository with EF 5 based on your generic repository with EF 6. The link below is the generic repository I am using my own project.
https://github.com/tugberkugurlu/GenericRepository

It is using DbContext instead of DataContext class so my repositories are something like that 

public class ProductRepository : BaseRepository<Product, int>, IProductRepository

 public abstract class BaseRepository<T, TId> : EntityRepository<T, TId> where T : class, IEntity<TId> where TId : IComparable

ProductRepository inheritances BaseRepository which inheritaces as you see. EntityRepository is using DBContext class for database operation and not supporting async methods right now. So I think I need to change DbContext  with DataContext like you did.. Every repository rely on DbContext as constructor parameter so it is so important to change core database operation to support async implementation for my project.

Any help really appreciated 

My Project ProductRepository
https://github.com/eminyuce/StoreManagement/blob/master/StoreManagement/StoreManagement.Service/Repositories/ProductRepository.cs
