### ISSUE TITLE
Return IQueryable

### ISSUE THREAD

**Issue by Nullception** [CypressNorth/.NET-EF6-GenericRepository#5]
I am curious why you decided to go with returning list objects vs IQueryables? Without the ability to retrieve IQueryable objects don't you limit access to linq extensions such as Include.

**Comment by mombrea** [comment]
That's a good point. I'd say the main reason is that you can't really have a distinction between synchronous and asynchronous without actually executing the query. There should probably be an additional method for the couple of list object functions which return IQueryable. 

In practice, we use a generic repository base similar to this one (this repo should get updated) and we create the IQueryable functions in the implementing services where appropriate. We don't use lazy loading in our application, so we typically have extension methods to chain on the IQueryable functions to include the desired navigation properties. 

To be honest, not enough thought was given toward how others might use this class, we simply added what we were using.
